### ISSUE TITLE
Use float64 as key in bptree

### ISSUE THREAD

**Issue by nrkfeller** [timtadh/data-structures#1]
As it currently stands. It seems I can only use "types.Int" as keys in the bptree is there a way we can use float64 instead?

**Comment by timtadh** [comment]
@nrkfeller you just need to implement the types.Hashable interface for float. I haven't implemented it because I haven't needed it yet. I just did a quick implementation in #2 . Please test that out and let me know if works. If you wanted to write a test that would be great as well but do not feel obligated.

**Comment by nrkfeller** [comment]
Beautiful! I will write tests when I have a bit of time. Thank you!
