### ISSUE TITLE
Tests break under Windows because of /dev/urandom

### ISSUE THREAD

**Issue by lkarlslund** [timtadh/data-structures#4]
Several places in your code, you open /dev/urandom directly, and use that to feed into math/rand.Seed(). This breaks Windows tests, as /dev/urandom is Linux only. 

Consider switching to crypto/rand.Read() as seed source instead, or just using current timestamp to seed with, that's universal.

Additionally in sortedset.go (init) you should not apply seeding. It's not really your library's responsibility to do so. For testing, modules, yes, but otherwise actually it's the programmers responsibility (perhaps they want to keep it unseeded for reproducable testing).

**Comment by timtadh** [comment]
Hi @lkarlslund 

Thanks for the bug report. I will try and put together a patch when I have a spare moment (but feel free to contribute one if you like). Some of this code (and the init's are part of it) comes from the pre-history of Go before there was a) windows support or b) rand.Read(). So that is likely why those init blocks are still around. I will check into whether ensure the randomization is necessary still. In the early days I don't think math/rand was seeded from a random source (it may be now).

**Comment by timtadh** [comment]
I just tagged [v0.5.2](https://github.com/timtadh/data-structures/releases/tag/v0.5.2) which includes #5 and should no longer reference /dev/urandom.
